# Production Docker Compose configuration
version: '3.8'

services:
  backend:
    build:
      context: ../backend/src
      dockerfile: ../../docker/dockerfile
      target: production
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com
      - CORS_ALLOWED_ORIGINS=https://yourdomain.com,https://www.yourdomain.com
    restart: unless-stopped
    # Add volume for static files in production
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend.dockerfile
      target: production
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=https://yourdomain.com/api
    depends_on:
      - backend
    restart: unless-stopped

  # Nginx reverse proxy (optional for production)
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
