version: '3.8'

services:
  backend:
    build:
      context: ../backend/src
      dockerfile: ../../docker/dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend/src:/app
      - /app/blogenv  # Exclude virtual environment from volume
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend.dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules  # Exclude node_modules from volume
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    depends_on:
      - backend
    restart: unless-stopped
